### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by baoxingsong** [smarco/WFA-paper#11]
I am using WFA to align some intergenetic sequences with very long indel (several tens of Kb), the reference sequence and query sequence maybe diverse a lot. For a pair of sequences with length < 25Kb, I am using the standard WFA. Otherwise WFA-Adaptive. and I set `mm_allocator_t* const mm_allocator = mm_allocator_new(BUFFER_SIZE_128M);`

Even I am running it on a PC with 512Gb ram, the program breaks due to out of memory. Of course, I do not expect WFA could align sequences with any length or any diversity. But is there any problem with my setting? How could I estimate the maximum memory usage, please?  Or could I catch an out of memory exception, please?

**Comment by smarco** [comment]
(1) The `mm_allocator_t` establishes the size of the memory chunks that are going to be used. It doesn't limit the overall memory that the WFA is going to use; just the way it requests memory from the system.

(2) In principle, I see no problem in your settings. _I can always double-check if you provide me with 2 sample sequences that cause the out-of-memory exception_. But, as you say, the WFA naturally has limitations and, at some point, it requires a lot of memory (most of all with highly divergent sequences).

(3) Memory usage is proportional to the difference between the sequences. The problem is that we don't usually know this magnitude in advance. 

For that, we are currently working in a more compact version of the WFA to further reduce the memory usage and possibly limit the overall maximum memory used. For the moment, I have no better answer. I hope to in the near future.
