### ISSUE TITLE
maybe a bug in WFA

### ISSUE THREAD

**Issue by cschin** [smarco/WFA-paper#19]
please take a look at this: https://gist.github.com/cschin/2cfe0bbbf7f7fee87d3669d2f307fffa

running affine_wavefronts_align() with the two strings in the `wfa_adapt.c` of the gist does not seem to generate correct results. It may hit some boundary cases for back-tracking.

**Comment by ekg** [comment]
Hi Jason, @smarco can confirm, but my impression is that the wavefront reduction can break some assumptions that affect the traceback. Increasing the reduction parameter (max_dist) should eventually resolve the boundary issue, and it shouldn't occur without reduction. In practice, we are checking for corruption of the traceback when using wavefront reduction. Perhaps there is a better solution.

**Comment by cschin** [comment]
@ekg that makes sense. If it hits some boundary cases with the `max_dist` for some difficult sequence pairs, maybe it makes sense to get a return status of a failed alignment status and the user can decide if they need to fall back to a more expensive setting.

**Comment by smarco** [comment]
In fact, it is a bug and a very interesting case. I took some time to push some other minor patches and run regression tests. 

**1)** In principle, the wavefront reduction is consistent with the general wavefront equations, and there is no reason it should generate broken alignments. Unless I introduce bugs, which happens to be the case -- my bad. Sadly, @ekg has found and suffered many of my bugs.

**2)** As @ekg is suggesting, those reduction parameters seem too tight. Particularly, in this example, it forces the algorithm to take a path that leads to quite a suboptimal alignment. But again, the threshold (10,50) is too tight for this specific case and lengths of ~16Kbp.

`(10,50) => Score = 504 (14163M49I155M1X35M1X8M1X4M1X43M1X1M1I97M1X4M1X35M1X33M1X15M1X7M1D49M1I25M1X114M1X57M1D49M1I75M1X15M1X7M1D49M1I25M1X73M1D41M1X7M1I41M1X57M1X4M1X93M49I51M49I18M1X49M1X30M1D18M1X49M1X48M1X49M1X48M1X49M1X48M1X308M)`

Being the optimal alignment the following:
`(-1,-1) => Score = 356 (14163M149I1291M1D18M1X49M1X30M1D18M1X49M1X48M1X49M1X48M1X49M1X48M1X308M)`

However, if you just raise it to (200,50), you get a much better adjustment.
`(200,50) => Score = 360 (14163M1X4M149I1286M1D18M1X49M1X30M1D18M1X49M1X48M1X49M1X48M1X49M1X48M1X308M)`

Or even if you choose to go (10,500), you hit the optimal alignment.
`(10,500) => Score = 356 (14163M149I1291M1D18M1X49M1X30M1D18M1X49M1X48M1X49M1X48M1X49M1X48M1X308M)`

The problem is to quickly discard solutions that are "left behind" by just 50 cells in the DP-matrix in cases with many exact matches and duplications.

**3)** Thanks for the example. I will look closely into it before the next WFA release. And don't hesitate to send any other bug report you may have.

**Comment by cschin** [comment]
@smarco I found this issue when I used (100,100) for the reduction parameters.  I was able to work around this case by reducing the gap extension panelity to 1.  I saw you have new commits. Let me know if the commits fix the problem. I can test it on various other data as well.

**Comment by smarco** [comment]
The commits should fix the problem. Let me know.
