### ISSUE TITLE
Readme comments

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/WFA-paper#21]
Section 2 is missing, and section 3.3 gives instruction for enabling 32bits, but it seems that this is already the case, so could be removed or changed to 'change to 16bit if your sequences are short'.

**Comment by smarco** [comment]
Thank you very much for the corrections. 

> Section 2 is missing

Corrected!

> Section 3.3 gives instruction for enabling 32bits, but it seems that this is already the case, so could be removed or changed to 'change to 16bit if your sequences are short'.

You are entirely correct. I set it to default because it was more natural to cover the general case (even at the loss of a little bit of performance).

I hope you can keep using the WFA in its new release [WFA2-lib](https://github.com/smarco/WFA2-lib/).
As always, all your comments, corrections, and feature requests are more than welcome.

Cheers
